#!/bin/bash

echo "🎮 === GUIDE D'OPTIMISATION DE LA FLUIDITÉ === 🎮"
echo ""
echo "💫 NOUVELLES OPTIMISATIONS APPLIQUÉES:"
echo "  ✅ Vitesse mouvement: 0.015 → 0.008 (plus fluide)"
echo "  ✅ Vitesse rotation: 0.015 → 0.008 (plus fluide)"
echo "  ✅ Suppression création/destruction image (plus performant)"
echo "  ✅ Rafraîchissement uniquement si mouvement"
echo ""
echo "🔧 POUR AJUSTER ENCORE PLUS (dans hook.c):"
echo ""
echo "🚶 MOUVEMENT (ligne ~112): move_speed = 0.008"
echo "  • Plus fluide/lent: 0.005, 0.003, 0.001"
echo "  • Plus rapide: 0.010, 0.015, 0.020"
echo ""
echo "🔄 ROTATION (ligne ~75): rot_speed = 0.008"
echo "  • Plus fluide/lent: 0.005, 0.003, 0.001"
echo "  • Plus rapide: 0.010, 0.015, 0.020"
echo ""
echo "⚡ FRÉQUENCE DE RENDU (pour économiser ressources):"
echo "  • Actuel: Rafraîchir à chaque mouvement"
echo "  • Option 1: Ajouter 'frame_count % 2 == 0' (1 frame sur 2)"
echo "  • Option 2: Ajouter 'usleep(1000)' dans handle_loop (pause micro)"
echo ""
echo "🎯 RECOMMANDATIONS SELON VOTRE MACHINE:"
echo "  💻 Machine puissante: move_speed=0.005, rot_speed=0.005"
echo "  🖥️  Machine moyenne: move_speed=0.008, rot_speed=0.008 (actuel)"
echo "  📱 Machine faible: move_speed=0.010 + limitation frame"
echo ""
echo "🧪 POUR TESTER DIFFÉRENTES VALEURS:"
echo "  1. Modifiez les valeurs dans src/raycasting/hook.c"
echo "  2. Tapez 'make' pour recompiler"
echo "  3. Lancez './cub3D maps/good/test_movement.cub'"
echo "  4. Testez WASD et flèches"
echo ""
echo "🚀 LANCEMENT DU TEST FLUIDE:"
echo "./cub3D maps/good/test_movement.cub"
